name: Deploy documentation

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/prod'
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v5
        with:
          cache: true
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          cname: "docs.bestium.jeme.cz"
